// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SC6_EntityFrameWork.DAL;

#nullable disable

namespace SC6_EntityFrameWork.DAL.Migrations
{
    [DbContext(typeof(TournamentContext))]
    [Migration("20250622231450_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SC6_EntityFrameWork.DAL.Models.Giocatore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroMaglia")
                        .HasColumnType("int");

                    b.Property<int>("SquadraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SquadraId");

                    b.ToTable("Giocatori");
                });

            modelBuilder.Entity("SC6_EntityFrameWork.DAL.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("SC6_EntityFrameWork.DAL.Models.Prenotazione", b =>
                {
                    b.Property<int>("SquadraId")
                        .HasColumnType("int");

                    b.Property<int>("TorneoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPrenotazione")
                        .HasColumnType("datetime2");

                    b.HasKey("SquadraId", "TorneoId");

                    b.HasIndex("TorneoId");

                    b.ToTable("Prenotazioni");
                });

            modelBuilder.Entity("SC6_EntityFrameWork.DAL.Models.Squadra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Squadre");
                });

            modelBuilder.Entity("SC6_EntityFrameWork.DAL.Models.Torneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("NumeroSquadre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Tornei");
                });

            modelBuilder.Entity("SC6_EntityFrameWork.DAL.Models.Giocatore", b =>
                {
                    b.HasOne("SC6_EntityFrameWork.DAL.Models.Squadra", "Squadra")
                        .WithMany("Giocatori")
                        .HasForeignKey("SquadraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Squadra");
                });

            modelBuilder.Entity("SC6_EntityFrameWork.DAL.Models.Prenotazione", b =>
                {
                    b.HasOne("SC6_EntityFrameWork.DAL.Models.Squadra", "Squadra")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("SquadraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SC6_EntityFrameWork.DAL.Models.Torneo", "Torneo")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Squadra");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("SC6_EntityFrameWork.DAL.Models.Torneo", b =>
                {
                    b.HasOne("SC6_EntityFrameWork.DAL.Models.Location", "Location")
                        .WithMany("Tornei")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("SC6_EntityFrameWork.DAL.Models.Location", b =>
                {
                    b.Navigation("Tornei");
                });

            modelBuilder.Entity("SC6_EntityFrameWork.DAL.Models.Squadra", b =>
                {
                    b.Navigation("Giocatori");

                    b.Navigation("Prenotazioni");
                });

            modelBuilder.Entity("SC6_EntityFrameWork.DAL.Models.Torneo", b =>
                {
                    b.Navigation("Prenotazioni");
                });
#pragma warning restore 612, 618
        }
    }
}
